version: '3.4'

services:
  devenv-eval-backend:
    image: devenv-eval-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - FLASK_APP=app.py
      - REDIS_HOST=redis
    ports:
      - 8080:8080
    networks:
      - dev
  redis:
    image: redis:7-alpine
    networks:
      - dev
networks:
  dev:
    name: devenv-eval-backend-dev
